sudo: required
dist: trusty
language: node_js
node_js: 7
branches:
  only:
  - master
deploy:
  provider: heroku
  app:
    master: moonfaces
  api_key:
    secure: sSR1GXOS78eB2lEyayaOteWKFo2Ov3/iA0V8/be5gYWtWlA1ZfhJJTygzbjERA7dOOrvGqEnVfUQ8xERDSYGABGGQ4S0sqoGfhKk5bLgDefToNjy2tjMTeYxcza5YU5iZqCt6zVKBMQcZkUaaDvIx8EKooIc01q4ZajSydWxn8SPLpfpiLvbo9HGnEUKPukMYYaXOGiqPJSik+0zViDJ94TVaK2ftly7R14Rlor17brCDfKzBGeSMYot4cRlPcWnTFGdX+BXNcPDsLI+rYDqom02HyQ9g8ZzzsOZY+FSWX9h5FcQHhRw++7U3l7+66Csf4jKJ0aPjg0EKu6ZcXHbUG2FTE+3sLP8jk7Mu1B1/fT7ZReXQKnBWopM0cIqs2V7NiBWu4Rre7HHU4VdKjLCxgZQKnNJdISn/ezTEKyFOYDAr+VShLtFtc/znN6gbjyWYE4vo8NiEPiKEXfhwfxH4JpxYTcyNAcor+xTEs4PVe2PMEh35MqsRSptAaV74pql54jmfveHezu1/93dZA7jF3RTz3HITMSq3JVYjK8idiZTiEDaTwzyrUPUhDQqNDAophh2URbzKV1Hd1RRDW4bXky432ZnJSwWJzLnnhj5MfPLVYmZ5tYCl445J3ecI5MUOT6htgtZmIs8tawjKjClw35zF4xBZkvGEFJmn6IogPI=
